---
title: 编程知识积累
date: 2022-01-19 10:21:59 +/-TTTT
categories: [exception, cpp]
tags: [exception, cpp, python]
---

# 目的
- 积累日常编程过程中的知识

# 异常与错误码
## 抛异常与错误码
首先，我们来分析一下抛异常和错误码相比的优缺点：
- 优点：
    1. 代码可读性高：在异常处理代码的try...catch...finally逻辑结构中，try是正常处理逻辑代码，catch是针对某种或者某类异常的异常处理代码，finally是资源清理代码。如此来看，各个功能的逻辑代码划分分门别类，看起来很清晰，代码可读性比较高
    2. 可以链式调用或者嵌套调用：在抛异常的处理方式下，可以使用add(sub())这种函数嵌套的调用方式以及add().sub()这种函数链式调用方式。然而如果采用返回错误码这种方式，正确的做法是：对于每个函数的执行，都需要我们首先获取其返回值，然后通过错误码判断函数执行的过程是否出现异常。因此是没办法使用嵌套调用或者链式调用的。
    3. 异常是无法忽略的。抛出的异常都必须通过catch来处理，也就是说异常是必须处理、无法忽略的。然而没有强制机制要求对错误码强制处理，返回的错误码完全可以被忽略。
    4. 由于抛出的异常是一个对象，因此在java中，可以采用多态的方式来处理。众所周知，多态的好处可以提高代码的扩展性
- 缺点：
    1. 然而抛出异常的方式在抛异常时，首先需要生成一个异常对象，并且需要维护一个栈用来跟踪异常情况，一直跟踪到我们捕捉到异常并且进行处理后截止，这样其实是比较耗费性能的。所以，与返回错误码相比的缺点就是性能低下。
    2. 在程序运行出现异常的时候，我们可以选择抛出异常或者返回错误码的方式来进行处理，那他们两个至今各有什么区别和优缺点，什么情况下应该选择什么方法呢？
## 应用场景
上面分析过，抛出异常的方式是比较耗费性能的，然而在程序正常处理、异常没有抛出的情况下，程序性能是不会受到影响的。由于上述所说的抛异常代码可读性高等四个优点，所以当我们觉得程序运行不会出现异常时，优先选择抛异常。如果可以预知程序可能会出错，为了性能考虑，那么则可以选择返回错误码。

那么什么情况是可以预知到程序运行会出现异常，什么情况下是预知程序不会出现异常呢？

可以预知到异常的情况：
1. 用户的输入，例如password错误等

可以预知程序不会出现异常:

1. 空指针，非法参数等
2. 资源错误：内存溢出、stack overflow等
## 个人总结
- 根据网络资料，大部分资料是觉得python这类脚本语言的异常和错误码各有优劣，没有高下之分
- 实际业务中对异常的处理有以下三个等级：
    1. 异常返回值（False、None、空等），脚本自行判断
    2. python抛异常，脚本大部分逻辑不会用try处理，这种可以视为有错误，中断当前流程，一般用于无法继续运行的情况
    3. 宕机。主动宕机（assert）的情况，一般是发现数据已经被损坏，无法复原，继续运行可能导致影响继续扩大
- 一般尽量使用情况1或者是根据返回值做特定处理，但如果是错误的话，容易被忽略，导致问题在开发阶段没有暴露
- 实际的c++编程中，本人很少以异常的方式来反馈错误
    - 一方面是因为定位错误时，异常很容易被忽略，因为这样做会打断上下文逻辑
    - 另一方面时因为c++经常混合c，但c不支持异常
- 异常相比于错误码，主要区别是可以跳出多层堆栈
    - 这种区别有好有坏
    - 优点是可以在较上层的调用处开发捕获逻辑
    - 缺点是这种跳出可能打断逻辑，没有执行完整逻辑，造成数据不完整。比如一段数据，只填了其中一部分，如果清理不及时，可能会对后续造成不可预知的影响
    - 如果某个接口可能抛出异常，要规避以上问题，最好的办法是就地加上try，但这样的逻辑多了之后，代码不够美观
## 参考文献
- [错误处理之异常与返回码](https://www.cnblogs.com/levy5307/articles/8723644.html)